# Generated by Django 4.1.4 on 2023-01-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="categories",
            name="category_image",
            field=models.ImageField(default="", upload_to="imgs/"),
        ),
    ]
