# Generated by Django 4.1.4 on 2023-01-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_categories_title_alter_categories_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="category_image",
            field=models.ImageField(upload_to="imgs/"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
