# Generated by Django 4.1.4 on 2023-01-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_categories_category_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="img/")),
                ("detail", models.CharField(max_length=600)),
            ],
        ),
    ]
