# Generated by Django 4.1.4 on 2023-01-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "news"},
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="news.categories",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="category_image",
            field=models.ImageField(default="", upload_to="imgs/"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
