# Generated by Django 4.1.4 on 2023-01-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_categories_options_alter_news_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="category_image",
            field=models.ImageField(upload_to="imgs/"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.categories"
            ),
        ),
    ]
