# Generated by Django 4.1.4 on 2023-01-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_categories_category_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="detail",
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(upload_to="imgs/"),
        ),
    ]
