# Generated by Django 4.1.4 on 2023-01-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_news_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="detail",
            field=models.TextField(),
        ),
    ]
