# Generated by Django 4.1.4 on 2023-03-16 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0010_favoritecategory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteCategory",
            new_name="UsersFavoriteCategory",
        ),
    ]
