# Generated by Django 4.1.4 on 2023-03-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0012_extrafield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafield",
            name="addresses",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
