# Generated by Django 4.1.4 on 2023-03-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0013_alter_extrafield_addresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafield",
            name="addresses",
            field=models.CharField(max_length=100),
        ),
    ]
