# Generated by Django 4.1.4 on 2023-03-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_alter_extrafield_addresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafield",
            name="addresses",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="extrafield",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
