# Generated by Django 4.1.4 on 2023-03-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0015_alter_extrafield_addresses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrafield",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
