# Generated by Django 4.1.4 on 2023-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0016_extrafield_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafield",
            name="birthday",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
