# Generated by Django 4.1.4 on 2023-03-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0020_alter_extrafield_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrafield",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
