# Generated by Django 4.1.4 on 2023-03-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0021_extrafield_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafield",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
