# Generated by Django 4.1.4 on 2023-03-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0022_alter_extrafield_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extrafield",
            name="gender",
        ),
    ]
