# Generated by Django 4.1.4 on 2023-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0024_extrafield_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafield",
            name="birthday",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="extrafield",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
