# Generated by Django 4.1.4 on 2023-03-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0025_alter_extrafield_birthday_alter_extrafield_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extrafield",
            old_name="birthday",
            new_name="birthdays",
        ),
        migrations.RenameField(
            model_name="extrafield",
            old_name="gender",
            new_name="genders",
        ),
    ]
