# Generated by Django 4.1.4 on 2023-03-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0026_rename_birthday_extrafield_birthdays_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extrafield",
            name="genders",
        ),
    ]
